---
permalink: san-host/concept_solaris_host_remediation.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, solaris, host, remediation 
summary: 'Se você estiver usando a ferramenta de transição de 7 modos (7MTT) para passar do ONTAP operando no modo 7 para o ONTAP em cluster em um ambiente SAN, você deve executar uma série de etapas no seu host Solaris antes e depois da transição para evitar complicações de transição.' 
---
= Correção do host Solaris
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando a ferramenta de transição de 7 modos (7MTT) para passar do ONTAP operando no modo 7D para o Clustered ONTAP em um ambiente SAN, você deverá executar uma série de etapas no seu host Solaris antes e depois da transição para evitar complicações de transição.

Os cenários a seguir não são compatíveis com nenhum fluxo de trabalho de transição (suporte para transições baseadas em cópia ou sem cópia):

* Transição de LUNs de inicialização SAN
+
Você pode configurar um LUN de inicialização SAN para funcionar em um ambiente DMP (Dynamic Multipathing) da Veritas ou em um ambiente MPxIO do Solaris executando os Utilitários de host e usando o protocolo FC. O método usado para configurar um LUN de inicialização SAN pode variar, dependendo do gerenciador de volumes e do sistema de arquivos.

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2748974["Guia de instalação e configuração do Solaris Host Utilities 6,2"]

* Transição de cluster de host Solaris
* Configuração do Veritas

