---
permalink: san-host/task_preparing_for_cutover_when_transitioning_linux_host_dmmp_device_without_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, linux, dmmp, device, host 
summary: Se você estiver fazendo a transição de um dispositivo DMMP sem um sistema de arquivos de um host Linux, há várias etapas que você deve executar antes de entrar na fase de transição. 
---
= Preparando-se para a transição ao fazer a transição de um dispositivo DMMP host Linux sem um sistema de arquivos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver fazendo a transição de um dispositivo DMMP sem um sistema de arquivos de um host Linux, há várias etapas que você deve executar antes de entrar na fase de transição.

Para configurações de FC, você precisa ter conectividade de malha e zoneamento para controladores Data ONTAP em cluster.

Para configurações iSCSI, suas sessões iSCSI devem ser descobertas e conetadas aos controladores Data ONTAP em cluster.

* Para transições baseadas em cópia, execute estas etapas antes de iniciar a operação de transferência de armazenamento na ferramenta de transição de 7 modos (7MTT).
* Para transições sem cópia, execute estas etapas antes de iniciar a operação Export & Halt 7-Mode no 7MTT.


.Passos
. Pare a e/S para os pontos de montagem.
. Encerre os aplicativos que estão acessando os LUNs de acordo com as recomendações do fornecedor do aplicativo.
. Lave o dispositivo ou alias LUN DMMP de 7 modos:
+
`*multipath -f _device_name_*`

+
Se necessário, você pode obter o nome do dispositivo DMMP na coluna *ID do dispositivo do sistema operacional* na guia SAN Host LUNs na _Inventory Assessment Workbook_.


