---
permalink: san-host/task_preparing_to_transition_san_boot_luns_on_hp_ux_hosts_with_fc_configurations.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, hp, ux, hosts, fc, configurations 
summary: Antes de fazer a transição de um LUN de inicialização SAN em um host HP-UX com uma configuração FC, você deve Registrar o nome do LUN de modo 7 no qual o HP-UX está instalado, o nome do dispositivo SCSI para esse LUN, a convenção de nomenclatura ágil e o WWID. 
---
= Preparando-se para a transição de LUNs de inicialização SAN em hosts HP-UX com configurações FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de fazer a transição de um LUN de inicialização SAN em um host HP-UX com uma configuração FC, você deve Registrar o nome do LUN de modo 7 no qual o HP-UX está instalado, o nome do dispositivo SCSI para esse LUN, a convenção de nomenclatura ágil e o WWID.

. No console do controlador 7-Mode, exiba seus LUNs 7-Mode para identificar o nome do LUN no qual o sistema operacional "'HPUX11v3 March 2014'" está instalado:
+
`*lun show*`

. Obtenha o nome do dispositivo SCSI para o LUN:
+
`*sanlun lun show -p*`

+
Neste exemplo, o LUN de transição é bootlun_94. Os dispositivos SCSI para este LUN são `/dev/dsk/c14t0d0`, `/dev/dsk/c27t0d0`, `/dev/dsk/c40t0d0`, e `/dev/dsk/c31t0d0` .

+
[listing]
----
        ONTAP Path: f8040-211-183:/vol/vol_183/bootlun_94
               LUN: 0
          LUN Size: 100g
       Host Device: /dev/rdisk/disk6
              Mode: 7
Multipath Provider: None
host      vserver   /dev/dsk
path      path      filename           host     vserver
state     type      or hardware path   adapter  LIF
-----     -------   ----------------   -------  -------
up        secondary /dev/dsk/c14t0d0   fcd0     fc4
up        primary   /dev/dsk/c27t0d0   fcd0     fc2
up        primary   /dev/dsk/c40t0d0   fcd1     fc1
up        secondary /dev/dsk/c31t0d0   fcd1     fc3
----
. Identifique o WWID para o LUN no host:
+
`*scsimgr get_info -D _SCSI_device_name_ |grep WWID*`

+
No exemplo a seguir, o WWID LUN para o dispositivo `/dev/rdisk/disk6` é 0x600a09804d537739422445386b75556:

+
[listing]
----
bash-2.05# scsimgr get_info -D /dev/rdisk/disk6 | grep WWID
World Wide Identifier (WWID)      = 0x600a09804d537739422445386b755564
bash-2.05#
----

