---
permalink: san-host/task_setting_up_esxi_hosts_configured_for_san_boot_after_transition.html 
sidebar: sidebar 
keywords: esxi, configured, boot, ontap, san, host, transition 
summary: Se o host ESXi foi configurado para inicialização SAN antes da transição do Data ONTAP operando no modo 7, você deve executar várias etapas antes de usar o host após a transição. 
---
= Configurando hosts ESXi configurados para inicialização SAN após a transição
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o host ESXi foi configurado para inicialização SAN antes da transição do Data ONTAP operando no modo 7, você deve executar várias etapas antes de usar o host após a transição.

* Para transições baseadas em cópia, execute estas etapas antes de iniciar a operação de transferência de armazenamento no 7MTT.
* Para transições sem cópia, execute estas etapas antes de iniciar a operação Export & Halt 7-Mode Systems no 7MTT.


.Passos
. Reconfigure seu BIOS HBA FC e FCoE para inicializar a partir do LUN de inicialização SAN do sistema Data ONTAP em cluster.
. Inicie o host ESXi.
. Redefina as configurações do host para as configurações de pré-transição.
. Para hosts iSCSI, consulte como reconfigurar seu iniciador iSCSI VMware.
+
xref:concept_reconfiguration_of_vmware_software_iscsi_initiator.adoc[Reconfigure o iniciador iSCSI da VMware]

. Remonte os datastores VMFS criados a partir do LUN de inicialização na instalação padrão.


*Informações relacionadas*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[Remontando volumes VMFS após a transição usando o vSphere Client]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[Remontando volumes VMFS após a transição usando a CLI ESXi]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["Administração da SAN"]
