---
permalink: san-host/task_testing_luns_with_mounts_using_dmmp_aliases_on_rhel_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, pints, dmmp, alias, name, rhel 
summary: 'Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para executar uma transição baseada em cópia do seu host do Red Hat Enterprise Linux (RHEL), você poderá testar seus LUNs Data ONTAP migrados em cluster com pontos de montagem usando nomes de alias antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.' 
---
= Testando LUNs com pontos de montagem usando nomes de alias DMMP em hosts RHEL antes da fase de transição de transições baseadas em cópia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para executar uma transição baseada em cópia do seu host Red Hat Enterprise Linux (RHEL), você poderá testar os LUNs Data ONTAP agrupados com pontos de montagem usando nomes de alias antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.

Os novos LUNs do Data ONTAP em cluster devem ser mapeados para o host de teste e os LUNs precisam estar prontos para a transição.

Você deve manter a paridade de hardware entre o host de teste e o host de origem e deve executar as etapas a seguir no host de teste.

Os LUNs do Data ONTAP em cluster estão no modo de leitura/gravação durante o teste. Eles convertem em modo somente leitura quando o teste estiver concluído e você estiver se preparando para a fase de transição.

.Passos
. Após a conclusão da cópia de dados da linha de base, selecione *modo de teste* na interface do usuário (UI) do 7MTT.
. Na IU do 7MTT, clique em *Apply Configuration*.
. Obtenha os novos nomes de dispositivos SCSI para os LUNs Data ONTAP em cluster:
+
`*sanlun lun show*`

+
No exemplo a seguir `/dev/sdl`, é o nome do dispositivo SCSI para `lun_dmmp_raw` o LUN `/dev/sdk` e é o nome do dispositivo SCSI para o.

+
`lun_dmmp_raw_alias` LUN:

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay)     lun-pathname               filename
-----------------------------------------------------------------
vs_brb     /vol/dmmp_raw_vol/lun_dmmp_raw              /dev/sdl
vs_brb     /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias  /dev/sdk
----
. Configure os dispositivos DMMP para os LUNs Data ONTAP em cluster:
+
`*multipath*`

. Obtenha as IDs de identificador do dispositivo para os LUNs Data ONTAP em cluster:
+
`*multipath -ll*`

+
O seguinte é um exemplo de um identificador de dispositivo ID: "'3600a09804d532d79565d47617679764d'"

. Verifique se um alias está definido no `/etc/multipath.conf` arquivo no host de origem.
. Copie manualmente a configuração de alias para o `/etc/multipath.conf` arquivo no host de teste, mas substitua o ID de identificador de dispositivo de 7 modos pelo ID de identificador de dispositivo Data ONTAP correspondente.
. Use o `multipath` comando para configurar dispositivos DMMP para seus LUNs Data ONTAP agrupados.
. Identificar o sistema de arquivos criado no dispositivo de alias DMMP:
+
`*blkid _dmmp_device_name_*`

. Monte o dispositivo DMMP:
+
`*mount*`

. Realize os testes conforme necessário.
. Depois de concluir o teste, desligue o host de teste:
+
`*shutdown -h -t0 now*`

. Na IU do 7MTT, clique em *Finish Testing*.


Para que os LUNs do Data ONTAP em cluster sejam remapeados para o host de origem, você deverá preparar o host de origem para a fase de transição. Se os LUNs do Data ONTAP em cluster permanecerem mapeados para o host de teste, não serão necessárias mais etapas no host de teste.

*Informações relacionadas*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Recolha de informações de pré-transição do livro de trabalho de avaliação de inventário]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Preparando-se para a fase de transição ao fazer a transição de LUNs com pontos de montagem usando nomes de dispositivos DMMP em hosts Linux]
