---
permalink: san-host/task_preparing_linux_guest_operating_systems_for_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, linux, operating, system 
summary: 'Se houver LUNs de 7 modos mapeados como RDM (PTRDM) para máquinas virtuais Linux (VMs) para o dispositivo de inicialização, há etapas que você deve executar para preparar suas VMs Linux para a transição.' 
---
= Preparando sistemas operacionais Linux Guest para transição
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se houver LUNs de 7 modos mapeados como RDM físico compatível (PTRDM) para máquinas virtuais Linux (VMs) para o dispositivo de inicialização, há etapas que você deve executar para preparar suas VMs Linux para a transição.

* Para transições baseadas em cópia, execute estas etapas antes de iniciar a operação de transferência de armazenamento na ferramenta de transição de 7 modos (7MTT).
* Para transições sem cópia, execute estas etapas antes de iniciar a operação Export & Halt 7-Mode Systems no 7MTT.


.Passos
. Obtenha os números de série do dispositivo SCSI:
+
`*cat /boot/grub/menu.lst*`

+
No exemplo a seguir, 360a9800032466879362b45777447462d-part2 e 360a980002466879362b45777774462d-part1 são números de dispositivo SCSI:

+
[listing]
----
# cat /boot/grub/menu.lst
...
kernel /boot/vmlinuz-3.0.13-0.27-default root=/dev/disk/by-id/scsi-
360a9800032466879362b45777447462d-part2 resume=/dev/disk/by-id/scsi-
360a9800032466879362b45777447462d-part1
----
. Determine o mapeamento entre os números de série do dispositivo SCSI e dispositivos/partições SCSI:
+
`*# ls -l /dev/disk/by-id*`

+
O exemplo a seguir mostra como o mapeamento de relacionamento é exibido. Os `SCSI devices/partitions` são apresentados seguindo a `SCSI device/partition serial numbers`. Neste exemplo, `../../sda, ../../sda1, and ../../sda2` são dispositivos/partições SCSI.

+
[listing]
----
lrwxrwxrwx 1 root root 9 Oct 27 06:54 scsi-360a9800032466879362b45777447462d -> ../../sda
   lrwxrwxrwx 1 root root 10 Oct 27 05:09 scsi-360a9800032466879362b45777447462d-part1 -> ../../sda1
   lrwxrwxrwx 1 root root 10 Oct 27 02:21 scsi-360a9800032466879362b45777447462d-part2 -> ../../sda2
----
. Determine o mapeamento entre os caminhos do dispositivo SCSI e os UUIDs:
+
`*ls -l /dev/disk/by-uuid*`

+
O exemplo a seguir mostra como o mapeamento de relacionamento é exibido. Neste exemplo, `33d43a8b-cfae-4ac4-9355-36b479cfa524` é o UUID para SCSI device/partição sda2', `603e01f8-7873-440a-9182-878abff17143` é o UUID para SCSI device/partition sdb, e `c50b757b-0817-4c19-8291-0d14938f7f0f` é o UUID para SCSI device/partition sda1.

+
[listing]
----
 lrwxrwxrwx 1 root root 10 Oct 27 02:21 33d43a8b-cfae-4ac4-9355-36b479cfa524 -> ../../sda2
   lrwxrwxrwx 1 root root 9 Oct 27 06:54 603e01f8-7873-440a-9182-878abff17143 -> ../../sdb
   lrwxrwxrwx 1 root root 10 Oct 27 05:09 c50b757b-0817-4c19-8291-0d14938f7f0f -> ../../sda1
----
. Use o UUID para atualizar a referência do dispositivo no arquivo de inicialização do grub `menu.lst`, combinando-o com o caminho do dispositivo SCSI e o número de série SCSI.
+
[listing]
----
#blkid
/dev/sda1: UUID="c50b757b-0817-4c19-8291-0d14938f7f0f" TYPE="swap"
/dev/sda2: UUID="33d43a8b-cfae-4ac4-9355-36b479cfa524" TYPE="ext3"
/dev/sdb: UUID="603e01f8-7873-440a-9182-878abff17143" SEC_TYPE="ext2" TYPE="ext3"
----
. Use o UUID que você acabou de recuperar para atualizar a referência do dispositivo no arquivo de inicialização do grub `menu.lst`.
+
O exemplo a seguir mostra o `menu.lst` arquivo depois que ele foi atualizado:

+
[listing]
----
# Modified by YaST2. Last modification on Fri Oct 17 02:08:40 EDT 2014
default 0
timeout 8
##YaST - generic_mbr
gfxmenu (hd0,1)/boot/message
##YaST - activate
###Don't change this comment - YaST2 identifier: Original name: linux###
title SUSE Linux Enterprise Server 11 SP2 - 3.0.13-0.27
root (hd0,1)
kernel /boot/vmlinuz-3.0.13-0.27-default root=/dev/disk/by-uuid/e5127cdf-8b30-
418e-b0b2-35727161ef41 resume=/dev/disk/by-uuid/d9133964-d2d1-4e29-b064-7316c5ca5566
splash=silent crashkernel=128M-:64M showopts vga=0x314
initrd /boot/initrd-3.0.13-0.27-default
----
. Atualize o `/etc/fstab` ficheiro:
+
.. Use o UUID que você acabou de recuperar para atualizar a referência do dispositivo no `/etc/fstab` arquivo.
+
O exemplo a seguir mostra um `/etc/fstab` arquivo com um número de série SCSI:

+
[listing]
----
/dev/disk/by-id/scsi-360a9800032466879362b45777447462d-part1 swap swap
defaults 0 0
/dev/disk/by-id/scsi-360a9800032466879362b45777447462d-part2 / ext3
acl,user_xattr 1 1
proc /proc proc defaults 0 0
sysfs /sys sysfs noauto 0 0
debugfs /sys/kernel/debug debugfs noauto 0 0
devpts /dev/pts devpts mode=0620,gid=5 0 0
----
.. Substitua a referência ao número de série SCSI pelo UUID.
+
O exemplo a seguir mostra um `/etc/fstab` arquivo que foi atualizado para substituir o número de série SCSI pelo UUID:

+
[listing]
----
cat /etc/fstab
UUID="c50b757b-0817-4c19-8291-0d14938f7f0f swap swap defaults
0 0
UUID="33d43a8b-cfae-4ac4-9355-36b479cfa524 / ext3 acl,user_xattr
1 1
proc /proc proc defaults 0 0
sysfs /sys sysfs noauto 0 0
debugfs /sys/kernel/debug debugfs noauto 0 0
devpts /dev/pts devpts mode=0620,gid=5 0 0
----



