---
permalink: san-host/task_testing_dmmp_devices_with_file_systems_on_rhel_hosts_before_cutover_phase.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, dmmp, devices, rhel, hosts, cutover, phase 
summary: 'Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para executar uma transição baseada em cópia do seu host do Red Hat Enterprise Linux (RHEL), você poderá testar os LUNs Data ONTAP migrados em cluster para verificar se você pode montar seu dispositivo DMMP antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.' 
---
= Testando dispositivos DMMP com sistemas de arquivos em hosts RHEL antes da fase de transição de transições baseadas em cópia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para executar uma transição baseada em cópia do seu host Red Hat Enterprise Linux (RHEL), você poderá testar os LUNs Data ONTAP migrados para verificar se é possível montar o dispositivo DMMP antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.

Os novos LUNs do Data ONTAP em cluster devem ser mapeados para o host de teste e os LUNs precisam estar prontos para a transição.

Você deve manter a paridade de hardware entre o host de teste e o host de origem.

Execute estas etapas no host de teste.

. Após a conclusão da cópia de dados da linha de base, selecione *modo de teste* na interface do usuário (UI) do 7MTT.
. Na IU do 7MTT, clique em *Apply Configuration*.
. Obtenha os novos nomes de dispositivos SCSI para os LUNs Data ONTAP em cluster:
+
`*sanlun lun show*`

+
No exemplo a seguir `/dev/sdl`, é o nome do dispositivo SCSI para o `lun_dmmp_raw` LUN `/dev/sdk` e é o nome do dispositivo SCSI para o `lun_dmmp_raw_alias` LUN:

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay) lun-pathname               filename
-----------------------------------------------------------
vs_brb  /vol/dmmp_raw_vol/lun_dmmp_raw              /dev/sdl
vs_brb  /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias  /dev/sdk
----
. Configure os dispositivos DMMP para os LUNs Data ONTAP em cluster:
+
`*multipath*`

. Obtenha o ID do identificador do dispositivo para os LUNs Data ONTAP em cluster:
+
`*multipath -ll*`

+
O seguinte é um exemplo de um identificador de dispositivo ID: "'3600a09804d532d79565d47617679764d'"

. Identificar o sistema de ficheiros configurado no dispositivo DMMP:
+
`*blkid | grep -i _device_handle_ID_*`

. Determine se existe uma entrada de ponto de montagem para o volume lógico no `/etc/fstab` arquivo no host de origem.
. Se existir uma entrada de ponto de montagem para o volume lógico no host de origem, edite manualmente o `/etc/fstab` arquivo no host de teste para adicionar as entradas de ponto de montagem.
. Montar o LUN:
+
`*mount -a*`

. Verifique se o dispositivo DMMP está montado:
+
`*mount*`

. Realize os testes conforme necessário.
. Depois de concluir o teste, desligue o host de teste:
+
`*shutdown -h -t0 now*`

. Na IU do 7MTT, clique em *Finish Testing*.


Para que os LUNs do Data ONTAP em cluster sejam remapeados para o host de origem, você deverá preparar o host de origem para a fase de transição. Se os LUNs do Data ONTAP em cluster permanecerem mapeados para o host de teste, não serão necessárias mais etapas no host de teste.

*Informações relacionadas*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Recolha de informações de pré-transição do livro de trabalho de avaliação de inventário]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Preparando-se para a fase de transição ao fazer a transição de LUNs com pontos de montagem usando nomes de dispositivos DMMP em hosts Linux]
