---
permalink: san-host/task_testing_data_luns_on_hp_ux_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, data, lun, hp, ux, citover, phase, copy, based 
summary: 'Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para executar uma transição baseada em cópia dos LUNs de dados do host HP-UX, você poderá testar os LUNs Data ONTAP migrados para verificar se você pode montar o dispositivo MPIO antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.' 
---
= Testando LUNs de dados em hosts HP-UX antes da fase de transição de transições baseadas em cópia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para realizar uma transição baseada em cópia dos LUNs de dados do host HP-UX, você poderá testar os LUNs Data ONTAP migrados em cluster para verificar se você pode montar o dispositivo MPIO antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.

Os novos LUNs do ONTAP devem ser mapeados para o host de teste e os LUNs precisam estar prontos para a transição

Você deve manter a paridade de hardware entre o host de teste e o host de origem, e deve executar as etapas a seguir no host de teste.

Os LUNs do ONTAP estão no modo de leitura/gravação durante o teste. Eles convertem em modo somente leitura quando o teste estiver concluído e você estiver se preparando para a fase de transição.

.Passos
. Após a conclusão da cópia de dados da linha de base, selecione *modo de teste* na interface do usuário (UI) do 7MTT.
. Na IU do 7MTT, clique em *Apply Configuration*.
. No host de teste, refaça a varredura de seus novos LUNs do ONTAP:
+
`*ioscan -fnC disk*`

. Verifique se os LUNs do ONTAP estão presentes:
+
`*sanlun lun show*`

. Copie o `/tmp/mapfile.vg01 mapfile` copiado anteriormente para sua fonte externa para o novo host.
. Use o mapfile para importar o grupo de volumes:
+
`*vgimport -s -m /tmp/mapfile/vg01 vg01*`

. Verifique se o `VG Status` é exibido como `available`:
+
`*vgdisplay*`

. Converta o nome de arquivo especial do dispositivo (DSF) legado para DSF persistente:
+
`*vgdsf -c /dev/vg01*`

. Use o comando mount para montar manualmente cada um dos volumes lógicos.
. Execute o `fsck` comando se você for solicitado a fazê-lo.
. Verifique os pontos de montagem:
+
`*bdf*`

. Realize os testes conforme necessário.
. Encerre o host de teste.
. Na IU do 7MTT, clique em *Finish Test*.


Se os LUNs do ONTAP precisarem ser remapeados para o host de origem, você deverá preparar o host de origem para a fase de transição. Se os LUNs do ONTAP precisarem permanecer mapeados para o host de teste, não serão necessárias mais etapas no host de teste.
