---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, enable, caw, datastore, esxi, cli 
summary: 'Se você não tiver suporte para comparar e escrever (CAW) no Data ONTAP operando no modo 7, você deve habilitar manualmente o suporte CAW quando fizer a transição para o Clustered Data ONTAP. O Clustered Data ONTAP suporta CAW por padrão.' 
---
= Habilitando o CAW em um datastore usando a CLI ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você não tiver suporte para comparar e gravar (CAW) no Data ONTAP operando no modo 7, você deve habilitar manualmente o suporte ao CAW ao fazer a transição para o Clustered Data ONTAP. O Clustered Data ONTAP suporta CAW por padrão.

* Não deve haver nenhuma e/S ou VMs em execução ativa no datastore VMFS.
* O datastore deve ser remontado, se ele tiver sido migrado.
* Você deve ter o novo ID de naa LUN do ONTAP a partir do arquivo de mapeamento da ferramenta de transição de 7 modos (7MTT).


A CAW deve ser ativada somente quando nenhuma e/S ou VMs estiver sendo executada ativamente no datastore VMFS.

* A CAW deve ser ativada somente quando nenhuma e/S ou VMs estiver sendo executada ativamente no datastore VMFS.
* Para transições baseadas em cópia, execute estas etapas após concluir a operação de transferência de armazenamento no 7MTT.
* Para transições sem cópia, execute estas etapas depois que a operação Importar dados e Configuração no 7MTT estiver concluída.


.Passos
. Abra o _Inventory Assessment Workbook_ gerado pela Inventory Collect Tool (ICT).
. Navegue até a guia sistemas de arquivos SAN Host.
. Verifique o status do CAW para o datastore.
+
O valor *ATS/CAW* para o datastore deve exibir *Disabled* e a coluna Filesystem deve exibir *VMFS.x*.

. Observe o nome do datastore na coluna disco
. Faça login no console ESXi usando SSH.
. Listar os detalhes do dispositivo e da partição:
+
`*~ # vmkfstools -Ph -v1 _datastore_path_*`

+
Datastore_path é o nome do datastore da coluna Disk do _Inventory Assessment Workbook_.

+
`*# vmkfstools -Ph -v1 /vmfs/volumes/datastorename*`

+
[listing]
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----
. Anote o primeiro nome do dispositivo e o número da partição.
+
No exemplo anterior `naa.600a098044314c6c442b446d51376749:1`, é o nome do dispositivo e o número da partição.

. Use o ID do dispositivo e o número da partição para ativar o CAW no datastore:
+
`*~# vmkfstools --configATSOnly 1 /vmfs/devices/disks/__device-ID:Partition__*`

. Verifique se o volume VMFS foi configurado somente com ATS:
+
`*# vmkfstools -Ph -v1 /vmfs/volumes/VMFS-volume-name*`

+
[listing]
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----


*Informações relacionadas*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[Remontando volumes VMFS após a transição usando o vSphere Client]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[Remontando volumes VMFS após a transição usando a CLI ESXi]

https://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.vsphere.storage.doc/GUID-6887003D-2322-49AC-A56C-7AFE7350DB5D.html["Documentação da VMware"]
