---
permalink: san-host/task_testing_transitioned_luns_on_aix_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, aix, cutover, phase, copy, based, test 
summary: 'Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para fazer a transição dos LUNs de host AIX, você pode testar os LUNs Data ONTAP migrados para verificar se você pode montar o dispositivo MPIO antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.' 
---
= Teste de LUNs transicionados em hosts AIX antes da fase de transição de transições baseadas em cópia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando a ferramenta de transição de 7 modos (7MTT) 2,2 ou posterior e o Data ONTAP 8.3,2 ou posterior para fazer a transição dos LUNs de host AIX, você pode testar os LUNs Data ONTAP migrados para verificar se é possível montar o dispositivo MPIO antes da fase de transição. O host de origem pode continuar executando e/S para os LUNs de 7 modos de origem durante o teste.

Os LUNs precisam estar preparados para a transição.

Você deve manter a paridade de hardware entre o host de teste e o host de origem e deve executar as etapas a seguir no host de teste.

Os LUNs do Data ONTAP em cluster estão no modo de leitura/gravação durante o teste. Eles convertem em modo somente leitura quando o teste estiver concluído e você estiver se preparando para a fase de transição.

.Passos
. Depois que a cópia de dados de linha de base estiver concluída, selecione *modo de teste* na interface do usuário (UI) do 7MTT.
. Na IU do 7MTT, clique em *Apply Configuration*.
. No host de teste, faça a nova varredura de seus novos LUNs do Data ONTAP em cluster:
+
`*cfgmgr*`

. Verifique se os novos LUNs do Data ONTAP em cluster estão presentes:
+
`*sanlun lun show*`

. Verifique o status do grupo de volumes:
+
`*lsvg vg_name*`

. Monte cada um dos volumes lógicos:
+
`*mount -o log/dev/loglv00 _file_system_mount_point_*`

. Verifique os pontos de montagem:
+
`*df*`

. Realize os testes conforme necessário.
. Encerre o host de teste:
+
`*shutdown -h*`

. Na IU do 7MTT, clique em *Finish Testing*.


Para que os LUNs do Data ONTAP em cluster sejam remapeados para o host de origem, você deverá preparar o host de origem para a fase de transição. Se os LUNs do Data ONTAP em cluster permanecerem mapeados para o host de teste, não serão necessárias mais etapas no host de teste.
