---
permalink: copy-based/concept_nfs_configurations_supported_unsupported_or_requiring_manual_steps_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, nfs, transition, supported, unsupported, required, manual, steps, configuration 
summary: Algumas configurações NFS não são transferidas para o ONTAP porque não são compatíveis com o ONTAP, há diferenças de funcionalidade em relação ao modo 7 ou devem ser transferidas manualmente. Você deve verificar todos os erros de pré-verificação e mensagens de aviso para avaliar o impactos de tais configurações na transição. 
---
= Transição NFS: Configurações com suporte e sem suporte, além de etapas manuais necessárias
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algumas configurações NFS não são transferidas para o ONTAP porque não são compatíveis com o ONTAP, há diferenças de funcionalidade em relação ao modo 7 ou devem ser transferidas manualmente. Você deve verificar todos os erros de pré-verificação e mensagens de aviso para avaliar o impactos de tais configurações na transição.



== Configurações compatíveis para transição

Em alto nível, as seguintes configurações NFS são transferidas pela ferramenta de transição de 7 modos:

* Opções de NFS:
+
** `nfs.udp.xfersize`
** `nfs.v4.id.domain`
** `nfs.v4.acl.max.aces`
** `nfs.tcp.xfersize`
** `nfs.rpcsec.ctx.high`
** `nfs.rpcsec.ctx.idle`
** `nfs.response.trigger`
** `wafl.default_nt_user`
** `nfs.mount_rootonly`
** `nfs.tcp.enable`
** `nfs.udp.enable`
** `nfs.response.trace`
** `nfs.v4.read_delegation`
** `nfs.v4.write_delegation`
** `nfs.v4.acl.enable`
** `nfs.vstorage.enable`
** `nfs.v3.enable`
** `nfs.v4.enable`


* Regra de exportação de NFS:
+
Se a regra de exportação estiver configurada com a `-actual` opção, o caminho exportado (caminho de alias) será ignorado e a regra de exportação será configurada com o caminho real.

* Regras de exportação com segurança Kerberos krb5p
* Configuração Kerberos


Consulte os resultados da pré-verificação para obter detalhes sobre essas configurações NFS.



== Configurações não suportadas no ONTAP

As seguintes configurações de NFS não são compatíveis com o ONTAP:

* Exportações de NFS de subvolume que não sejam exportações de NFS no nível de qtree
* WebNFS
* PC-NFS
* NFSv2
* Cerco de clientes NFS a partir de um ou mais caminhos de sistema de arquivos
* Algumas opções de NFS
+
Consulte as mensagens de aviso de pré-verificação para obter uma lista completa de opções não suportadas.





== Configurações que devem ser transferidas manualmente

Existem algumas configurações NFS compatíveis com o ONTAP, mas não são transferidas pela ferramenta de transição de 7 modos.

As configurações NFS a seguir geram uma mensagem de aviso na operação de pré-verificação e você precisa aplicar manualmente as configurações no SVM:

* Configuração de auditoria NFS
* Opções de NFS:
+
** `rpc.nsm.tcp.port`
** `rpc.nsm.udp.port`
** `rpc.mountd.tcp.port`
** `rpc.mountd.udp.port`
** `nfs.export.neg.timeout`
** `nfs.export.pos.timeout`
** `nfs.export.harvest.timeout` Use o `vserver nfs modify` comando para modificar a configuração de uma máquina virtual de storage (SVM) habilitada para NFS.


* Regras de exportação com segurança Kerberos krb5p




== Configurações que são funcionalmente diferentes no ONTAP

As seguintes configurações NFS são funcionalmente diferentes no ONTAP:

* Regras de exportação de NFS
* Cache de acesso de exportação NFS
* Comandos de diagnóstico NFS
* Suporte para o `showmount` comando
* Criptografia NFS Kerberos
* Suporte à versão NLM


*Informações relacionadas*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html["Gerenciamento de NFS"]
