---
permalink: copy-based/task_running_precheck_on_a_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, run, prechecks 
summary: Depois de criar uma sessão de transição, você pode validar a sessão para verificar se o ambiente 7-Mode pode ser transicionado usando o comando transition precheck. Você pode verificar a compatibilidade entre o sistema de storage 7-Mode e o SVM para fatores como recursos e configurações de segurança. 
---
= Execução de pré-verificações
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de criar uma sessão de transição, você pode validar a sessão para verificar se o ambiente 7-Mode pode ser transicionado usando o `transition precheck` comando. Você pode verificar a compatibilidade entre o sistema de storage 7-Mode e o SVM para fatores como recursos e configurações de segurança.

A sessão de transição deve estar no estado de preparação.

O `transition cbt precheck` comando gera um relatório de mensagem de erro detalhado. Os problemas identificados no relatório recebem diferentes níveis de gravidade, dependendo do impactos do problema no processo de transição. Como alguns erros podem dificultar a transição, você deve executar ações corretivas para erros e avisos. Você também deve analisar o impactos de mensagens de outros níveis de gravidade antes de prosseguir com a transição.

.Passos
. Verifique a compatibilidade para a transição:
+
`*transition cbt precheck -p _project_name_*`

+
[listing]
----
7-Mode Transition Tool>transition cbt precheck -p project_finance

[1/14 ] Project status checks                                                  [    Errors     ]

Operation summary:
------------------
The 'precheck' operation on the project 'project_finance' has failed.

 1  Errors - Failed!

Do you want to see a detailed report {yes, no} [yes]:

1 Errors:
---------
90202: Checking whether any of the 7-Mode volumes are in 'offline' state.                              [     Error     ]
  > Following volumes are in 'offline' state.
  > CORRECTIVE-ACTION: Bring offline volumes online by using the following command: 'vol online
  > <volume_name>'.
  > AFFECTED-OBJECTS: { vol2 }

Next suggested steps:
---------------------
1. Review the 'precheck' operation results, fix all blocking errors and run the 'precheck' operation again.
2. Use the 'transition job-results -j 6e33e0a7-bb36-49df-91f3-2e52cbfa3074' command to see the results of this
operation.

Ran precheck for project 'project_finance'.
----


Você deve resolver todos os erros que podem causar problemas com a transição antes de iniciar a cópia de dados dos volumes do 7-Mode.
