---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: Você pode iniciar uma cópia de dados de volumes do modo 7 para volumes do ONTAP para uma transferência de linha de base. A transferência da linha de base começa quando as agendas de cópia de dados configuradas em um projeto se tornam ativas. Após a conclusão da transferência da linha de base, os volumes do ONTAP são atualizados periodicamente com base no agendamento de cópia de dados. 
---
= Iniciar cópia de dados para um projeto de transição
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode iniciar uma cópia de dados de volumes do modo 7 para volumes do ONTAP para uma transferência de linha de base. A transferência da linha de base começa quando as agendas de cópia de dados configuradas em um projeto se tornam ativas. Após a conclusão da transferência da linha de base, os volumes do ONTAP são atualizados periodicamente com base no agendamento de cópia de dados.

* Você deve ter executado uma pré-verificação no projeto e resolvido todos os erros.
* Você deve ter configurado uma rede dedicada, de alta largura de banda e baixa latência entre os sistemas de origem e destino para transferência de dados.
+

NOTE: Você pode usar multipathing SnapMirror para equilibrar a carga de transferência de dados entre os dois caminhos.

* Uma programação de cópia de dados deve ser configurada para a sessão.


Se você estiver migrando para uma SVM existente, os volumes serão criados durante essa operação. Se você estiver migrando para um novo SVM, o SVM e seus volumes serão criados durante essa operação.

As relações do SnapMirror são criadas entre o modo 7 e o ONTAP volumes.

.Passos
. Inicie a cópia de dados:
+
`*transition start -p _project_name_*`

+
Se a operação de início falhar e a cópia de dados não for iniciada, você deverá resolver os problemas e executar o `transition start` comando novamente.

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
O projeto muda para o estado Copy-Baseline (cópia-linha de base). Após a conclusão da transferência da linha de base, o projeto passa para o estado de cópia-atualização.


