---
permalink: copy-based/task_starting_baseline_data_copy.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, baseline, copy 
summary: Depois de criar um projeto e concluir a operação de pré-verificação, você deve iniciar a cópia de dados dos volumes do modo 7 para o ONTAP. Você pode iniciar a operação de cópia de dados de linha de base para projetos individuais. Você deve parar processos desnecessários do sistema e atividade da rede durante a cópia de dados. 
---
= Iniciar cópia de dados da linha de base
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de criar um projeto e concluir a operação de pré-verificação, você deve iniciar a cópia de dados dos volumes do modo 7 para o ONTAP. Você pode iniciar a operação de cópia de dados de linha de base para projetos individuais. Você deve parar processos desnecessários do sistema e atividade da rede durante a cópia de dados.

Você deve ter criado pelo menos uma agenda de cópia de dados.

Você pode estimar o tempo para concluir as transferências de linha de base e avaliar a performance obtida pelas transferências de volume SnapMirror no seu ambiente executando uma migração de teste. A seguir estão alguns dos fatores que podem afetar o desempenho:

* Opções de agendamento de cópia de dados de transição selecionadas
+
Essa programação controla o número máximo de transferências simultâneas do SnapMirror e a largura de banda máxima a ser usada para as transferências.

* Número máximo de transferências simultâneas de SnapMirror de volume suportadas pelos controladores de origem do modo 7
* Largura de banda de rede entre a fonte de 7 modos e os controladores de destino ONTAP
+
O tráfego de rede não relacionado à atividade de migração deve ser minimizado para que a taxa de transferência seja maximizada e o tempo de resposta seja minimizado entre os sistemas de origem e destino.

* Funcionalidades de performance das controladoras de origem e de destino
+
Os sistemas de origem e destino devem ter a melhor utilização da CPU e memória disponível.

* Número de transferências SnapMirror de volume de 7 modos que ocorrem durante a cópia de dados


.Passos
. No Dashboard, selecione o projeto para o qual deseja iniciar a cópia de dados da linha de base.
. Clique em *Start Baseline*.
+
A pré-verificação é executada novamente em segundo plano e, se não forem detetados erros, a transferência da linha de base é iniciada com base na programação de cópia de dados. A caixa de diálogo progresso da operação exibe as informações sobre o status das operações de pré-verificação executadas durante a cópia de dados da linha de base.

. Clique na guia *volumes* para exibir o status e o progresso da transferência da linha de base.
+
Para visualizar os detalhes detalhados do SnapMirror de cada volume, clique em *Exibir detalhes da transição*. O número de transferências de SnapMirror simultâneas é baseado na entrada fornecida na programação que está ativa atualmente. Você pode acompanhar a programação ativa na guia Agenda de cópia de dados no Dashboard.

+
Após a conclusão da operação de cópia de dados da linha de base, as atualizações incrementais do SnapMirror começam com base na programação fornecida durante a criação do projeto.



*Informações relacionadas*

xref:task_creating_schedule_for_snapmirror_transfers.adoc[Criação de um agendamento de cópia de dados para transferências SnapMirror]
