---
permalink: install-admin/task_uninstalling_7_mode_transition_tool_on_linux.html 
sidebar: sidebar 
keywords: ontap, 7, mode, install, uninstall, transition, tool, linux 
summary: Você pode desinstalar a ferramenta de transição 7-Mode no Linux usando a interface de linha de comando. 
---
= Desinstalar o 7-Mode Transition Tool no Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desinstalar a ferramenta de transição 7-Mode no Linux usando a interface de linha de comando.

* Você deve ter concluído todas as transições em andamento.
+

IMPORTANT: Instalar uma versão mais recente ou reinstalar a mesma versão da ferramenta não permite que você acesse as operações de transição iniciadas pela instância desinstalada.

* Se a ferramenta de transição de 7 modos estiver em execução, ela deve ser parada.


O JRE não é removido como parte da desinstalação.

.Passos
. Desinstale a 7-Mode Transition Tool executando o seguinte comando do local onde você extraiu a 7-Mode Transition Tool:
+
`*./unconfigure*`

. Remova o diretório 7-Mode Transition Tool:
+
.. `*cd ..*`
.. `*rm -rf NetApp_7ModeTransitionTool*`






== Exemplo

[listing]
----

bash-4.2# cd /root/Downloads/extracted_folder/NetApp_7ModeTransitionTool
bash-4.2# ./unconfigure
bash-4.2# cd ..
bash-4.2# rm -rf NetApp_7ModeTransitionTool
----