---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: Você pode fazer a transição dos pares de HA primário e secundário que contêm os volumes de uma relação de SnapMirror de 7 modos em paralelo. Em seguida, você deve configurar manualmente a relação volume SnapMirror no Clustered Data ONTAP após a transição. A relação SnapMirror é mantida após a transição sem exigir uma nova linha de base. 
---
= Transição de sistemas primários e secundários em uma relação SnapMirror em paralelo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer a transição dos pares de HA primário e secundário que contêm os volumes de uma relação de SnapMirror de 7 modos em paralelo. Em seguida, você deve configurar manualmente a relação volume SnapMirror no Clustered Data ONTAP após a transição. A relação SnapMirror é mantida após a transição sem exigir uma nova linha de base.

Você precisa ter preparado os clusters de origem e destino para fazer a transição dos relacionamentos do SnapMirror.

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[Preparando o cluster para fazer a transição das relações do volume SnapMirror]

É necessário fazer a transição dos pares de HA secundário e primário na mesma janela de transição.

.Passos
. Na ferramenta de transição de 7 modos, execute uma transição livre de cópias dos dois pares de HA que contêm os volumes primário e secundário da relação do volume SnapMirror de 7 modos.
+
Antes de fazer a transição do par de HA de 7 modos que contém os volumes secundários, nenhuma intervenção manual é necessária para as relações de SnapMirror de 7 modos. Isso garante que os volumes secundários do modo 7 sejam transferidos como volumes somente leitura para o ONTAP.

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[Transição de agregados 7-Mode usando transição livre de cópia]

. Crie uma relação entre clusters SVM entre os SVMs que contêm os volumes primário e secundário transferidos.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["Administração do sistema"]

. Crie uma relação de volume SnapMirror entre os volumes primário e secundário transferidos.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html["Preparação expressa da recuperação de desastres de volume"]

. No volume de destino, ressincronize o volume de origem e o volume de destino da relação SnapMirror:
+
`*snapmirror resync*`

+

IMPORTANT: Pelo menos uma cópia Snapshot comum deve existir entre os volumes de origem e destino.

+
*Solução de problemas:* a ressincronização do SnapMirror falha se a cópia Snapshot comum tiver sido criada em uma versão do Data ONTAP anterior a 8,1. Você pode usar o `-fs-version` parâmetro com o `volume snapshot show` comando no nível de privilégio avançado para exibir a liberação na qual a cópia Snapshot foi criada. Se você encontrar esse problema, quebre a relação do SnapMirror e execute a ressincronização.

. Monitore o status das transferências de dados do SnapMirror:
+
`*snapmirror show*`

+

IMPORTANT: Não é necessário executar nenhuma operação, como movimentação de volume ou quebra de SnapMirror, nos volumes de origem e destino até que a ressincronização seja concluída com êxito. Certifique-se de que a ressincronização não seja abortada e concluída com sucesso; caso contrário, os volumes podem ir para um estado inconsistente.

. Comprometer a transição do projeto secundário, seguido do projeto primário.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[Comprometendo o projeto de transição livre de cópias]



*Informações relacionadas*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandos ONTAP 9"]

https://docs.netapp.com/us-en/ontap/["System Manager"]
