---
permalink: snapmirror/reference_7_mode_ontap_version_requirements_for_transitioning_volumes_using_snapmirror.html 
sidebar: sidebar 
keywords: ontap, 7, mode, version, transition, requirements, data, clustered 
summary: Você deve estar ciente das versões do Data ONTAP que operam no modo 7 que são suportadas para a transição para o Clustered Data ONTAP 8.3 ou posterior. 
---
= Requisitos de versão do 7-Mode para transição
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das versões do Data ONTAP que operam no modo 7 que são suportadas para a transição para o Clustered Data ONTAP 8.3 ou posterior.

Se o sistema 7-Mode tiver apenas agregados e volumes de 64 bits, você poderá fazer a transição de volumes de sistemas que executam as seguintes versões 7-Mode para o Clustered Data ONTAP 8.3 ou posterior:

* Data ONTAP 8,0
* Data ONTAP 8.0,1
* Data ONTAP 8.0,2
* Data ONTAP 8.0,3
* Data ONTAP 8.0,4
* Data ONTAP 8.0,5
* Data ONTAP 8,1
* Data ONTAP 8.1,2
* Data ONTAP 8.1,3
* Data ONTAP 8.1,4
* Data ONTAP 8,2
* Data ONTAP 8.2,1
* Data ONTAP 8.2,2
* Data ONTAP 8.2,3
* Data ONTAP 8.2,4
* Data ONTAP 8.2,5


Se o sistema de 7 modos estiver executando o Data ONTAP 8.0.x, 8,1.x ou 8,2 e tiver agregados ou volumes de 32 bits com cópias Snapshot de 32 bits, será necessário atualizar para 8.1.4 P4 ou 8,2.1. Após a atualização, você deve expandir os agregados de 32 bits para 64 bits e, em seguida, localizar e remover quaisquer dados de 32 bits.

Você deve atualizar as seguintes versões do modo 7 para o Data ONTAP 8.1,4 P4 antes de fazer a transição para o Clustered Data ONTAP 8.3 ou posterior:

* Data ONTAP 7.3.3
* Data ONTAP 7.3.4
* Data ONTAP 7.3.5
* Data ONTAP 7.3.6
* Data ONTAP 7.3.7

